apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup-cronjob
  namespace: kube-system
spec:
  schedule: "0 0/4 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          # Tolerate master taint
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          hostNetwork: true
          containers:
          - name: etcd-backup
            image: docker.io/ahmadrafiee/etcd-mc:v3.5.6-2023-08-01
            args:
            - https://127.0.0.1:2379
            volumeMounts:
            - mountPath: /var/lib/etcd
              name: etcd-datadir
            - mountPath: /certs
              name: etcd-certs
            env:
              - name: MINIO_ALIAS_NAME
                value: mecan
              - name: MINIO_SERVER
                value: https://object.kube.<DOMAIN>
              - name: MINIO_BUCKET
                value: etcd-backup
              - name: MINIO_API_VERSION
                value: S3v4
              - name: MINIO_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: etcd-backup-secret
                    key: MINIO_ACCESS_KEY
              - name: MINIO_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: etcd-backup-secret
                    key: MINIO_SECRET_KEY
          volumes:
          - name: etcd-datadir
            hostPath:
              path: /var/lib/etcd
          - name: etcd-certs
            hostPath:
              path: /etc/kubernetes/pki/etcd/
          restartPolicy: Never

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup-secret
  namespace: kube-system
type: Opaque
data:
  MINIO_ACCESS_KEY: "ZXRjZC1iYWNrdXA="
  MINIO_SECRET_KEY: "dnNkY3Nmd2VlazdCYkhHZGRzZGV3N1Y3M1hnYmpnVw=="
