mode: standalone

image:
  repository: quay.io/minio/minio
  tag: RELEASE.2024-10-29T16-01-48Z
  pullPolicy: IfNotPresent

rootUser: "dfseoijlwmemsdepoqwvm2"
rootPassword: "akPEKIvsdcsfek7BbHGd7V73XgbjgWSB5hvnKwxyZKJzQU"

mountPath: "/data"

resources:
  requests:
    memory: 1G
    cpu: 500m
  limit:
    memory: 5G
    cpu: 1000m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi

environment:
  MINIO_SERVER_URL: https://object.kube.<DOMAIN>
  MINIO_BROWSER_REDIRECT_URL: https://minio.kube.<DOMAIN>

service:
  name: minio-api
  type: ClusterIP
  port: "9000"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-http01-edit-in-place: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  path: /
  hosts:
    - object.kube.<DOMAIN>
  tls:
    - secretName: object-tls-secret
      hosts:
        - object.kube.<DOMAIN>

consoleService:
  name: minio-console
  type: ClusterIP
  port: "9001"

consoleIngress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-http01-edit-in-place: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  path: /
  hosts:
    - minio.kube.<DOMAIN>
  tls:
    - secretName: minio-tls-secret
      hosts:
        - minio.kube.<DOMAIN>

