---
apiVersion: v1
data:
  auth: dGVjaG5vbGlmZTokYXByMSRiclYvd0R4cCRiTkswVTdSZ2dsbHdvSlpFb1UvVEkwCgo=
kind: Secret
metadata:
  name: alertmanager-auth
  namespace: monitoring
type: Opaque
---
apiVersion: v1
data:
  auth: dGVjaG5vbGlmZTokYXByMSRiclYvd0R4cCRiTkswVTdSZ2dsbHdvSlpFb1UvVEkwCgo=
kind: Secret
metadata:
  name: prometheus-auth
  namespace: monitoring
type: Opaque