---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mongodb
  labels:
    app: mongodb-pay-1
spec:
  type: NodePort
  ports:
   - name: mongodb-deployment
     protocol: TCP
     port: 27017
     targetPort: 27017
     nodePort: 30032
  selector: 
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb-pay
    app.kubernetes.io/name: mongodb
    statefulset.kubernetes.io/pod-name: mongodb-pay-1
